### ISSUE TITLE
NameError (uninitialized constant OperationsController::PhpProcess)

### ISSUE THREAD

**Issue by joeblack81** [kaspernj/php_process#5]
this error appears when I try to call the gem from my action.
Please advice .

**Comment by kaspernj** [comment]
Hi Joe.

I need more information in order to debug your problem.

I assume you are doing something like this?
```ruby
require "php_process"
PhpProcess.new do |php|
  php.func(:echo, "Hello world")
end
```

**Comment by kaspernj** [comment]
@joeblack81 Did you fix it yourself? :-)

**Comment by joeblack81** [comment]
Ya it worked , I added the files to /lib and installed missing dependencies.

Thanks

**Comment by kaspernj** [comment]
Great :-)
