### ISSUE TITLE
stack level too deep

### ISSUE THREAD

**Issue by shiva-prasad-12** [kaspernj/php_process#7]
I am using in ruby 1.8.7  and installed gem php_process i am getting error  SystemStackError: stack level too deep please help me out to fix it .  
 
require "rubygems"
require "php_process"

Php_process.new do |php|
  php.func("require_once", "#{File.dirname(__FILE__)}/PHPExcel/PHPExcel.php")
  objPHPExcel = php.new("PHPExcel")

         /gems/ruby-1.8.7-head/gems/tsafe-0.0.11/lib/tsafe.rb:7:in `const_missing'
         /gems/ruby-1.8.7-head/gems/tsafe-0.0.11/lib/tsafe.rb:9:in `const_missing'
         /gems/ruby-1.8.7-head/gems/php_process-0.0.12/lib/php_process.rb:43:in `initialize'
	from (irb):24:in `new'

**Comment by kaspernj** [comment]
I am not supporting 1.8 in any of my projects, so first of all I would suggest you upgrade to a more recent version of Ruby. Preferably > 2.0.

I can see you aren't calling the current file path correctly (by calling `__FILE__`), but instead you are calling the file constant (by calling `FILE`). Try with this instead:

```ruby
require "rubygems"
require "php_process"

Php_process.new do |php|
  php.func("require_once", "#{File.dirname(__FILE__)}/PHPExcel/PHPExcel.php")
  objPHPExcel = php.new("PHPExcel")
```

**Comment by shiva-prasad-12** [comment]
Hello kasper
I have tried with the above code also , which you have sent and i have downloaded  the PHPExcel and suggest me where to add that folder either in vendor or public folder right now i added that folder in public.

Thank You

**Comment by kaspernj** [comment]
I have attempted to fix the autoloader. It is on master. Update like this:

```ruby
gem "php_process", github: "kaspernj/php_process"
```

Or:
```bash
gem update php_process
```

**Comment by shiva-prasad-12** [comment]
I have done that in rails 4 and 2 but its showing nothing to update.

Thank You


Thanks & Regards,

*Shiva Prasad A*
Mobile: +91-9902746713

[image: FaceBook] <https://www.facebook.com/shiv.prasad.3344>  [image:
Google+] <https://plus.google.com/u/1/+ShivPrasad6006> [image: Linked In]
<https://in.linkedin.com/in/shiva-prasad-967029b9>

**Comment by kaspernj** [comment]
If you cannot upgrade the version in your project, then I cannot help you. Sorry.

**Comment by shiva-prasad-12** [comment]
Hello kasper,

I have downloaded your code and add to lib folder in rails 4 application.
getting error like PhpProcess::DestroyedError .
The below code is what i executed 
php = PhpProcess.new
php.func("require_once", "#{File.dirname(__FILE__)}/PHPExcel/PHPExcel.php")
PhpProcess::DestroyedError: PhpProcess::DestroyedError

can you please suggest me what is the reason for this.

Thank You.

**Comment by shiva-prasad-12** [comment]
Hello kasper ,

I have fixed that issue by replacing this code.
php.func("require_once", "#{File.dirname( __ FILE __ )}/public/PHPExcel/PHPExcel.php")
Thank You
