### ISSUE TITLE
Not  able to add image to xlsx file using php process gem in rails 4

### ISSUE THREAD

**Issue by shiva-prasad-12** [kaspernj/php_process#8]
I  am able to add values to xlsx file and is this gem supports to add image to xlsx ? 

Thank you

**Comment by kaspernj** [comment]
This gem is not specifically for working with XLSX files. It should support whatever PHP does.

**Comment by shiva-prasad-12** [comment]
Hello kasper,
How do we include php class in ruby file , those classes are been defined in PHPExcel Folder with .php file extension. 

Thank You

**Comment by kaspernj** [comment]
This is how you spawn a new proxy-object of a given PHP class:

```ruby
object = php.new("PHPExcel_Worksheet_MemoryDrawing")
```

**Comment by shiva-prasad-12** [comment]
Hi kaspernj

Thanks for your help , where do get syntax to call php methods  example getting error like  undefined method `imagecreatefromjpeg' for #<PhpProcess:0x0000000265ff70>

'gdImage = php imagecreatefromjpeg('1.jpg')
objDrawing.setImageResource(gdImage)

uninitialized constant PHPExcel_Worksheet_MemoryDrawing for below code
objDrawing.setRenderingFunction(PHPExcel_Worksheet_MemoryDrawing::RENDERING_JPEG)'

If you suggest me with this two errors almost i finish adding image.

Thanks For All Your Help

**Comment by kaspernj** [comment]
Take a look at the README here: https://github.com/kaspernj/php_process

**Comment by shiva-prasad-12** [comment]
Hello kasper,

Thanks for your support , how do we call php inbuilt function  imagecreatefromjpeg('file.name') , i am getting undefined method  imagecreatefromjpeg i didn't find code to call inbuilt function in README here: https://github.com/kaspernj/php_process.

Thanks

**Comment by kaspernj** [comment]
@shiva-prasad-12 I have added an example, so it is shown how to call functions on the README with the headline "Calling functions". Does that help you? :-)

**Comment by shiva-prasad-12** [comment]
Hello kasper ,

I have tried with that and getting error 

> PHP Warning: imagejpeg() expects parameter 1 to be resource, integer given
> php_process->`error_handler'
> `imagejpeg'

Code

`image = php.func("ImageCreateFromJPEG", "12.jpeg")
gdImage = php.func("ImageJPEG", image, "new_filename.jpeg", 85)
objDrawing = php.new("PHPExcel_Worksheet_MemoryDrawing")
objDrawing.setImageResource(gdImage)`

**Comment by kaspernj** [comment]
You are using the `ImageJPEG` function in PHP wrong. That function is used to write images and returns an integer, which you pass to `.setImageResource`. Since the gem looks like to work as expected, I will close this issue :-)

**Comment by shiva-prasad-12** [comment]
Hello kasper

i just followed the steps which you have have give , if you know a syntax to to send image path please share with so that i can use it . I am try to add image to xls file from last month . Please help me out with this .

Thank You

**Comment by kaspernj** [comment]
If you want general help with PHP, then I would take it to StackOverflow. These issues are for the PhpProcess gem and not for general PHP- or Ruby issues.
